Feature/sticky add button
wearejust/sonata-theme-bundle pull request #12
Opened 2017-08-21 13:27 UTC by bartjust

Sticky add button

## Changelog

```markdown
### Added
- Added functionality to make the add button sticky on scroll

```

2017-08-21 19:46 UTC, ceesvanegmond submitted a review, later dismissed

2017-08-22 12:07 UTC, Emroni requested changes

2017-08-22 12:07 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +let minWidth = 940;
Tip: gebruik CONST MIN_WIDTH = 940;
Variabelen die nooit veranderen noem je constantes (const) en schrijf je met hoofdletters.

2017-08-22 12:07 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +	if($window.width() > minWidth) {
Als je bij initialisatie al checkt op grootte, werkt het niet als je op desktop een klein scherm groot trekt. De width vergelijking **altijd** in een resize functie stoppen.

2017-08-22 12:07 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +		addBtnClone = $('.add_records').clone().appendTo('.navbar-collapse');
Liever de clone al in de HTML zetten en hier selecteren, dan dat je hem hier clonet en helemaal aanpast (classes op/af, etc).

2017-08-22 12:07 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +$window.resize(function() {
Maak liever een **function resize()** aan, want dan kun je die rechtstreeks met resize() aanroepen, ipv $window.resize, Je kan hem dan ook exporteren en zo buiten de module gebruiken.

2017-08-22 12:07 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +			$('.add_records.js-sticky').show();
Meerdere keren een element selecteren? Altijd vermijden! Maak een var aan en selecteer het element on init, waarmee je hem later kan aanroepen in resize functies. Als een gebruiker zijn browser van groot naar klein (of andersom) sleept, wordt dit 100x afgevuurd en kan dat problemen veroorzaken (performance, vertraging in resizen).

2017-08-25 09:54 UTC, RutgerKooijman submitted a review, later dismissed

2017-08-25 11:50 UTC, bartjust commented
@Emroni resolved the merge conflicts. Can you give it a last check and merge it?

2017-08-25 12:21 UTC, ceesvanegmond requested changes
@bartjust Why remove the .github/CODEOWNERS file?

2017-08-25 12:25 UTC, bartjust commented
@ceesvanegmond Not sure what happened there. Didn't remove it, but I did have it in my unstaged files apparently.

2017-09-21 13:47 UTC, johnhout commented
@bartjust Please resolve the conflict 👍

2017-10-02 11:56 UTC, bartjust commented
@johnhout merge conflicts are resolved

2017-10-02 12:19 UTC, johnhout submitted a review, later dismissed

2017-10-02 20:30 UTC, ceesvanegmond submitted a review, later dismissed

2017-10-06 11:52 UTC, Emroni submitted a review, later dismissed

2017-10-06 11:52 UTC, Emroni commented on Resources/public/javascript/sticky.js
> +}
Best practice is to wrap the if and else statements with another if to check if it is already shown/hidden, so it doesnt run multiple times unnecessarily. eg:

```javascript
if($window.width() >= MIN_WIDTH) {
	if (!cloneShown) {
		cloneShown = true;
		clone.css('left', element.not('.js-sticky').offset().left);
		clone.show();
	}
} else if (cloneShown) {
	cloneShown = false;
	clone.css('left', '');
	clone.hide();
}
```

2017-10-31 11:15 UTC, ceesvanegmond commented
@bartjust Could you pick up last suggestion of @Emroni ?

2017-11-02 14:28 UTC, bartjust commented
@Emroni @ceesvanegmond Last changes are pushed to the feature branch. Should be ready to be merged now. Can you give it a last check?

2017-11-02 14:54 UTC, ceesvanegmond commented
@bartjust 👍  @Emroni Could you do final check?

2017-11-02 14:54 UTC, ceesvanegmond submitted a review, later dismissed

2017-11-02 15:00 UTC, ceesvanegmond submitted a review, later dismissed

2017-11-02 15:11 UTC, ceesvanegmond approved these changes

2017-11-02 15:11 UTC, merged