Feature: Added styling for Cropper
wearejust/sonata-theme-bundle pull request #21
Opened 2017-10-06 10:35 UTC by ceesvanegmond

## Title
Added styling for Cropper feature in https://github.com/wearejust/form-bundle/blob/1.x/Resources/doc/formtypes/image.md

## Changelog

```markdown
### Added
- Added some new CSS specifically for cropper
- Added new JS to make cropper more UI friendly
```

2017-10-06 11:43 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +
Why use an entire class if the only thing it does it fire **$('*[name="btn_update_and_edit"]').click();**? Just doing this should work too:

$('*[data-method="getCroppedCanvas"]').on('click', function() {
    $('*[name="btn_update_and_edit"]').click();
});

2017-10-06 11:45 UTC, RutgerKooijman submitted a review, later dismissed
@bartjust Looks good, maybe better to remove empty line ins .cropper class between classnames.

2017-10-06 11:55 UTC, Emroni requested changes

2017-10-06 11:55 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +        cropTrigger = $('*[data-method="getCroppedCanvas"]');
You should use **this.item.find()** here

2017-10-06 11:55 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +let cropTrigger;
Move this to the constructor

2017-10-06 11:55 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +class cropSave {
Try to use the same class name as the selector at the bottom, eg: .cropper -> Cropper.

2017-10-06 12:06 UTC, bartjust commented
@Emroni I've refactored the code. Multiple croppers can be used without problems now.

2017-10-06 12:38 UTC, Emroni requested changes

2017-10-06 12:38 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +        this.item.find($('*[data-method="getCroppedCanvas"]')).on('click', this.save.bind(this));
Almost! 
find( **$(** '*[data-method="getCroppedCanvas"] '**)** )
should be without the **$()**
find('*[data-method="getCroppedCanvas"]')

2017-10-06 12:39 UTC, Emroni commented on Resources/public/javascript/cropper.js
> +        if(!updateBtn.length) return;
So the only function this class has is to save, but why should the class exist in the first place if there is not save button available?

2017-10-23 12:38 UTC, bartjust commented
@Emroni The cropper js is removed as the functionality for triggering the save is not preferred anymore. The cropper will now have its default behaviour. This branch only has adjusted styling.

2017-10-24 09:20 UTC, merged